security:

    role_hierarchy:
        ROLE_ADMIN: ROLE_EDITOR
        ROLE_EDITOR: ROLE_USER

    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:

        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Login will be added in the next step.
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                success_handler: App\Security\LoginSuccessHandler

            logout:
                path: app_logout

    access_control:

        # Public authentication routes.
        - { path: ^/login$, roles: PUBLIC_ACCESS }

        # Everything under the dashboard requires authentication.
        - { path: ^/dashboard, roles: ROLE_USER }